formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Exclude some linters from running on tests files.
      - path: util/proxy_test.go
        linters:
          - revive
      - path: util/proxy.go
        linters:
          - revive
version: "2"
